Repository colory-games/Unreal-VerseBeginnerEdition-Samples, pull requests merged in 2023-11, with the labels that each got.

#1 Add: Sample Source Code
  Samples/chapter_03/device_sample_arithmetic.verse
  Samples/chapter_03/device_sample_case.verse
  Samples/chapter_03/device_sample_class.verse
  Samples/chapter_03/device_sample_comment.verse
  Samples/chapter_03/device_sample_const.verse
  Samples/chapter_03/device_sample_for.verse
  Samples/chapter_03/device_sample_function.verse
  Samples/chapter_03/device_sample_function_namearg.verse
  Samples/chapter_03/device_sample_if.verse
  Samples/chapter_03/device_sample_loop.verse
  Samples/chapter_03/device_sample_variable.verse
  Samples/chapter_03/device_sample_variable_editable.verse
  Samples/chapter_04/detatype_sample_array.verse
  Samples/chapter_04/detatype_sample_basic.verse
  Samples/chapter_04/detatype_sample_class.verse
  Samples/chapter_04/detatype_sample_enum.verse
  Samples/chapter_04/detatype_sample_map.verse
  Samples/chapter_04/detatype_sample_struct.verse
  Samples/chapter_04/detatype_sample_tuple.verse
  Samples/chapter_05/compound_sample_class.verse
  Samples/chapter_05/compound_sample_enum.verse
  Samples/chapter_05/compound_sample_interface.verse
  Samples/chapter_05/compound_sample_module.verse
  Samples/chapter_05/compound_sample_struct.verse
  Samples/chapter_05/compound_sample_subclass.verse
Labels: enhancement

#2 Add: Basic Files of Sample Source Code Repository
  .gitattributes
  CHANGELOG.md
  CODE_OF_CONDUCT.md
  github/CONTRIBUTING.md
  github/FUNDING.yml
  github/ISSUE_TEMPLATE/bug.md
  github/ISSUE_TEMPLATE/feature-request.md
  github/workflows/lint.yaml
  github/workflows/release.yaml
Labels: documentation

#3 Fix: .github Directory Name
  .github/CONTRIBUTING.md
  .github/FUNDING.yml
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/workflows/lint.yaml
  .github/workflows/release.yaml
Labels: bug

#4 Update: Readme
  README.md
Labels: documentation

#6 Fix: Error on the Release Process
  .github/workflows/release.yaml
Labels: bug
